DROP TABLE IF EXISTS user;
		
CREATE TABLE user (
  id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  username VARCHAR(25) NOT NULL,
  password VARCHAR(50) NOT NULL DEFAULT 'NULL',
  createdAt TIMESTAMP NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (id)
);

-- ---
-- Table 'post'
-- 
-- ---

DROP TABLE IF EXISTS post;
		
CREATE TABLE post (
  id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  user_id INTEGER NULL DEFAULT NULL,
  title VARCHAR(25) NULL DEFAULT NULL,
  code VARCHAR NULL DEFAULT NULL,
  summary VARCHAR NULL DEFAULT NULL,
  createdAt TIMESTAMP NULL DEFAULT NULL,
  anonymous bit NULL DEFAULT NULL,
  closed bit NULL DEFAULT NULL,
  solution INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

-- ---
-- Table 'comment'
-- 
-- ---

DROP TABLE IF EXISTS comment;
		
CREATE TABLE comment (
  id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  user_id INTEGER NULL DEFAULT NULL,
  post_id INTEGER NULL DEFAULT NULL,
  message VARCHAR NULL DEFAULT NULL,
  votes INTEGER NULL DEFAULT NULL,
  solution bit NULL DEFAULT NULL,
  createdAt TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
